/*
  Brief-Given 4 n-digit integers,from which a pin is generated by using the minimum of the digits of the all 4 integers. With the pin above
  generated we use it to encrypt a message.
  */
import java.util.*;
public class BasicEncryption {
	public static void main(String[] args) {
		Scanner sc=new Scanner(System.in);
		int n,num1,num2,num3,num4;
		System.out.println("Enter the value of n: ");
		n=sc.nextInt();
		System.out.println("Enter the first integer: ");
		num1=sc.nextInt();
		System.out.println("Enter the second integer: ");
		num2=sc.nextInt();
		System.out.println("Enter the third integer: ");
		num3=sc.nextInt();
		System.out.println("Enter the fourth integer: ");
		num4=sc.nextInt();
		int a=0,b,c,d,e;
		while(num1!=0) {
			b=num1%10;
			c=num2%10;
			d=num3%10;
			e=num4%10;
			a=a*10+(Math.min(b, Math.min(c, Math.min(d, e))));
			num1=num1/10;
			num2=num2/10;
			num3=num3/10;
			num4=num4/10;}
		int pin=0;
		int f=a;
		while(a!=0) {
			int g=a%10;
			pin=(pin*10)+g;
			a=a/10;}
		System.out.println("pin: "+pin);
		String h="very difficult to break";
		String i="";
		for(int j=0;j<h.length();j++) {
			if(h.charAt(j)!=' ')
				i=i+h.charAt(j);
		}
		i=i.toUpperCase();
		int k=f;
		String l="";
		for(int j=0;j<i.length();j++)
		{
			char m=(char)(i.charAt(j)+(f%10));
			if(m>90)
				m=(char)(m-26);
			l=l+m;
			f=f/10;
			if(f==0)
				f=k;
		}
		
		i=i.toLowerCase();
		System.out.println("The message is: "+i);
		System.out.println("The encrypted format for the message is: "+l);
		
		

	}

}
